HARMONY-900: Npm audit updates
nasa/harmony pull request #424
Opened 2023-06-28 15:02 UTC by vinnyinverso

## Jira Issue ID
HARMONY-900

## Description
Fixes security issues (build failure) discovered upon merging in the previous harmony-900 PR.

## Local Test Steps
run `npx better-npm-audit` audit for each package.json

## PR Acceptance Checklist
* [ ] Acceptance criteria met
* [ ] Tests added/updated (if needed) and passing
* [ ] Documentation updated (if needed)

2023-06-29 13:51 UTC, chris-durbin commented
I saw gdal-async is updated to the version that doesn't work on our EC2 instances - we need to lock gdal-async to 3.5.0.

Leo and James commented before the way to do this is update package.json to set gdal-async to ~3.5.0 instead of  ^3.5.0 and then run `npm install` again.
```
git show 14d53dd3 | grep gdal-async
     "node_modules/gdal-async": {
-      "resolved": "https://registry.npmjs.org/gdal-async/-/gdal-async-3.5.0.tgz",
+      "resolved": "https://registry.npmjs.org/gdal-async/-/gdal-async-3.7.0.tgz",
     "gdal-async": {
-      "resolved": "https://registry.npmjs.org/gdal-async/-/gdal-async-3.5.0.tgz",
+      "resolved": "https://registry.npmjs.org/gdal-async/-/gdal-async-3.7.0.tgz",
```

2023-06-29 13:52 UTC, chris-durbin requested changes
Lock gdal-async at 3.5.0 prior to merging.

2023-06-29 17:30 UTC, chris-durbin approved these changes
Deployed and tested in sandbox - was able to submit requests that included reprojection which use the gdal-async library.

2023-06-30 12:56 UTC, ygliuvt approved these changes

2023-06-30 14:36 UTC, merged