Support getting history of deployments for a service and listing running services (or any given status)
nasa/harmony pull request #564
Opened 2024-04-18 20:19 UTC by indiejames

## Jira Issue ID
HARMONY-1749

## Description
Adds support for listing deployments that have been done for a particular service as well as listing deployments by status,
e.g., got get the running deployment.

## Local Test Steps
Do a service  deployment
```
curl -Ln -bj -XPUT "http://localhost:3000/service-image-tag/query-cmr" -H 'Authorization: bearer <your token>' -d '{"tag": "latest"}' -H 'Content-type: application/json'
```
List all service deployments
```
curl -Ln -bj "http://localhost:3000/service-image-tag/deployment"
```
List service deployments for query-cmr
```
curl -Ln -bj "http://localhost:3000/service-image-tag/deployment?service-id=query-cmr"
```
List service deployments by status
```
curl -Ln -bj "http://localhost:3000/service-image-tag/deployment?status=failed"
```

## PR Acceptance Checklist
* [x] Acceptance criteria met
* [x] Tests added/updated (if needed) and passing
* [x] Documentation updated (if needed)

2024-04-19 14:30 UTC, indiejames commented on services/harmony/app/frontends/service-image-tags.ts
> +  for (const validation of validations) {
I'll add a coment explaing that 'no status' is a valid choice.

2024-04-19 14:31 UTC, indiejames commented on services/harmony/app/frontends/service-image-tags.ts
> +      const deployments = await getDeployments(tx, queryLowerCase.status, queryLowerCase.serviceid);
Vinny's fault :). I agree, `service` would be better. Done.

2024-04-19 14:31 UTC, indiejames commented on services/harmony/app/models/service-deployment.ts
> +  Omit<ServiceDeployment, 'deployment_id' | 'id' | 'validate' | 'save' | 'serialize'> &
Ask Vinny?

2024-04-19 15:40 UTC, indiejames commented on services/harmony/app/frontends/service-image-tags.ts
> +  if (status) {
I added a comment that passing no status was a valid choice - we only validate 'status' if it is present.

2024-04-19 15:41 UTC, indiejames commented on services/harmony/app/frontends/service-image-tags.ts
> +    const validStatuses = Object.values(ServiceDeploymentStatus).map((val) => JSON.stringify(val));
I add case-insensitiviy to the 'status' check

2024-04-19 17:22 UTC, chris-durbin commented on services/harmony/app/frontends/service-image-tags.ts
> +    const validStatuses = Object.values(ServiceDeploymentStatus).map((val) => JSON.stringify(val));
There needs to be a sad emoji for my disappointment in TypeScript.

2024-04-19 20:32 UTC, ygliuvt commented on docs/guides/managing-existing-services.md
We should update the documentation on `GET /service-deployments-state` endpoint.

2024-04-22 12:21 UTC, chris-durbin approved these changes

2024-04-22 12:28 UTC, ygliuvt requested changes
Failed to test locally, getting the following error with `service-deployments-state` PUT requests:
```
User undefined is not in the admin EDL group
```
The issue is caused by the new service-deployment* routes are not in the `authorizedRoutes` list. We can add `'/service-deployment*',` in the `authorizedRoutes` list to fix the issue.

2024-04-22 13:28 UTC, indiejames commented on docs/guides/managing-existing-services.md
Done.

2024-04-22 13:29 UTC, indiejames commented
> Failed to test locally, getting the following error with `service-deployments-state` PUT requests:
> 
> ```
> User undefined is not in the admin EDL group
> ```
> 
> The issue is caused by the new service-deployment* routes are not in the `authorizedRoutes` list. We can add `'/service-deployment*',` in the `authorizedRoutes` list to fix the issue.

Good catch. I added '/service-deployment*' to `authorizedRoutes`.

2024-04-22 14:01 UTC, ygliuvt requested changes
I found query with both `service` and `status` not working. e.g. when I test locally the following query: `http://localhost:3000/service-deployment?service=giovanni-adapter&status=successful` returns the only harmony-service-example service deployment that is successful. We can support this a separate ticket.

2024-04-22 14:28 UTC, ygliuvt approved these changes

2024-04-22 15:35 UTC, merged