DAS-2180: Update the HyBIG service invocation parameter.
nasa/harmony pull request #602
Opened 2024-06-26 21:15 UTC by flamingbear

This is for v2.0.0 of HyBIG where image generation library is [mostly] separate from the harmony service code.

## Jira Issue ID

[DAS-2180](https://bugs.earthdata.nasa.gov/browse/DAS-2180)

## Description

As part of separating business logic from harmony service logic, the calling parameter for the service has changed in HyBIG.

This change will require harmony redeployments each time HyBIG v2 is promoted.

## Local Test Steps

Pull the HyBIG branch for v2, build and test the local HyBIG image.
Branch: https://github.com/nasa/harmony-browse-image-generator/tree/mhs/DAS-2180/extract-lib
PR: TBD

Pull this branch and build Harmony. 
(I don't know exactly how to make sure this is picked up, so I would do a full rebuild of this branch and a bootstrap of Harmony-In-A-Box.)

Ensure you don't have any .env file that overrides `HYBIG_INVOCATION_ARGS`.

Run the HyBIG harmony regression tests against your local Harmony-In-A-Box to ensure the service is being invoked correctly.

## PR Acceptance Checklist
* [N/A] Acceptance criteria met
* [N/A] Tests added/updated (if needed) and passing
* [N/A] Documentation updated (if needed)

2024-07-23 19:40 UTC, flamingbear commented
It's been a minute since Harmony-In-A-Box tests have passed, and they take forever, fix or nix?

2024-08-01 01:10 UTC, owenlittlejohns requested changes
I tested this branch with the updated version of HyBIG and it all worked nicely.

I think the one missing thing is updating the `ENV_CHANGELOG.md`, to track these changes. (Sorry for the nit)

2024-08-01 01:51 UTC, owenlittlejohns approved these changes
Thanks for the quick update!

2024-08-01 20:32 UTC, indiejames approved these changes

2024-08-01 20:42 UTC, merged