Harmony 933 concatenate parameter
nasa/harmony pull request #88
Opened 2021-10-22 16:21 UTC by indiejames

Adds the 'concatenate' parameter along with OpenAPI validation, etc., but only enables it for tests for now since the actual code to run the CONCISE service will not be added until HARMONY-959-662.

2021-11-01 19:38 UTC, indiejames commented on app/middleware/earthdata-login-token-authorizer.ts
> +    } else if (req.headers.cookie) {
Fixed with help from @bilts . Removed this code since it is unnecessary.

2021-11-01 20:42 UTC, chris-durbin approved these changes

2021-11-03 13:30 UTC, bilts requested changes
I think the logic for `supportsOperationsOtherThanConcatenation` needs to change or the use of that method needs to be removed to allow for cases where PO.DAAC wants to chain services into CONCISE and have concatenation be an optional part of that.

Note: the ticket number is 993 not 933.  Please make sure commit messages have that number moving forward to help with release notes.

2021-11-03 13:30 UTC, bilts commented on app/models/services/index.ts
> +  if (requiresConcatenation(operation)) {
I disagree with Chris :-/ at least as written.  If the _only_ capability is concatenation, maybe we skip it, but PO.DAAC will usually be chaining CONCISE with other services, so in those cases, we'll want to use the flag to run / skip CONCISE based on whether the param was set.

2021-11-03 13:30 UTC, bilts commented on app/models/services/index.ts
> +  if (serviceConfig.name === 'noOpService' && operation.shouldConcatenate) {
I'll just go ahead and agree that unprocessed links are weird.

2021-11-03 13:30 UTC, bilts commented on app/routers/router.ts
> +      console.log('ok');
Remove (this should be a linter issue)

2021-11-03 13:30 UTC, bilts commented on test/concatenation.ts
> +    describe('is requested for a collection that has no service that provides concatenation', function () {
See test/models/services.ts. - we have ways to provide an explicit alternative service config set to whatever we want.

2021-11-03 13:43 UTC, chris-durbin commented on app/models/services/index.ts
> +  return configs.filter((config) => !getIn(config, 'capabilities.concatenation', false));
Oh reading this logic I see the issue. The intent is that we should not send a request to a service chain that requires concatenation. That should not be based on the `capabilities`. If we want to revert this change and write a separate ticket I'd be good with that.

2021-11-03 16:34 UTC, indiejames commented on app/routers/router.ts
> +      console.log('ok');
Done. Should not have been committed.

2021-11-03 20:33 UTC, chris-durbin commented on test/concatenation.ts
> +    describe('is requested for a collection that has no service that provides concatenation', function () {
We should defer this test to the new ticket which will make sure that services that would skip concatenation are not used.

2021-11-05 13:25 UTC, bilts approved these changes

2021-11-05 14:07 UTC, merged